import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [conversion, setConversion] = useState('')
  const [convertible, setConvertible] = useState('')

  //this function handles submitting the item to be converted to the backend (while specifying 
// the conversion type), then placing the conversion in state once received
  const convert = (conversionType) => {
    fetch(`/api/convert?conversionType=${conversionType}`, {
      method: "POST",
      headers: {'Content-Type': "application/json"},
      body: JSON.stringify({"convertible": convertible})
    })
    .then((res) => res.json())
    .then(data => setConversion(data.conversion))
  }

//validates the users input and either sends the fetch with the correct conversionType or gives 
//message to user that input was incorrect
  const validateInput = () => {
    let conversionType = ''
    //using some regex for input validation/checking which way to convert
    if (/^[0-9]+$/.test(convertible)){
      conversionType = 'toRoman'
      convert(conversionType)
    } else if (/^[MDCLXVI]+$/.test(convertible)) {
      conversionType = "toNum"
      convert(conversionType)
    } else if  (/^[mdclxvi]+$/.test(convertible)) {
      setConversion("Roman Numerals must be capitalized.")
    }
    else {
      setConversion("You have not entered a valid number or Roman Numeral")
    }
    
  }

  //this function updates the state variables that hold the users input of integer or roman num
  const updateInput = (event) => {
    setConvertible(event.target.value)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>When In Rome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        <h1 className={styles.title}>
          When in Rome
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Enter a Roman Numeral or Integer&rarr;</h2>
            <div className={styles.grid}>
            <input type={'text'} onChange={updateInput}></input>
            <button className={styles.button} onClick={validateInput}>CONVERT</button>
            </div>
          </div>

          <div className={styles.card}>
            
            <div className={styles.grid}>{conversion == '' ? <p>Conversion will appear here.</p> : <p>{conversion}</p>}</div>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by Sullivan Pierce with Next.js, deployed with
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
