import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [conversion, setConversion] = useState('')
  const [convertible, setConvertible] = useState('')


  const convert = () => {
    fetch('/api/convert?conversionType=toRoman', {
      method: "POST",
      headers: {'Content-Type': "application/json"},
      body: JSON.stringify({"convertible": convertible})
    })
    .then((res) => res.json())
    .then(data => setConversion(data.conversion))
  }

  //this function updates the state variables that hold the users input of integer or roman num
  const updateInput = (event) => {
    setConvertible(event.target.value)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>When In Rome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          When in Rome
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Enter a Roman Numeral or Integer&rarr;</h2>
            <div className={styles.form}>
            <input type={'text'} onChange={updateInput}></input>
            <button onClick={convert}>CONVERT</button>
            <p>{convertible}</p>
            </div>
          </div>

          <div className={styles.card}>
            
            {conversion == '' ? <p>Conversion will appear here</p> : <p>{conversion}</p>}
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by Sullivan Pierce, deployed with
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
